### ISSUE TITLE
REDTEST#13: Save audit information to a database

### ISSUE THREAD

**Issue by reddepruebas** [reddepruebas/www#13]
# Description

**User:** system.
**I Want:** save, in the database, the final state of each operation executed by each system user.
**In order to:** create an audit register in database to future queries.

**Criteria:**
1.Execute a system operation and look in the database that its final state is saved.
# Issue Links
# Sub-Tasks
1. [ ] [Create domain objects to save audit information to database.](https://github.com/reddepruebas/www/issues/29)
2. [ ] [Create methods to save audit information.](https://github.com/reddepruebas/www/issues/30)
3. [ ] [Use created methods to save final states in system operations.](https://github.com/reddepruebas/www/issues/31)
