### ISSUE TITLE
REDTEST#5: Apply log levels on code

### ISSUE THREAD

**Issue by reddepruebas** [reddepruebas/www#5]
# Description

**User:** system.
**I Want:** include logging levels in the source code using [Apache Log4j 2](http://logging.apache.org/log4j/2.x/).
**In order to:** control logging output.

**Criteria:**
1. Review that our logging format document follows The Apache Log4j 2 specification.
2. Review all Java source files and check that its sentences of logs look like the specification document.
3. Testing each logging level and compare to logging format established.
# Issue Links

_This issue clones:_ [REDTEST#9: Include exception's trace into notification email service](https://github.com/reddepruebas/www/issues/9)
# Sub-Tasks
1. [x] [Investigate how to use The Apache Log4j 2 specification and create a logging format document with it.](https://github.com/reddepruebas/www/issues/26)
2. [ ] [Include logging levels in the source code using logging format's document.](https://github.com/reddepruebas/www/issues/27)
3. [ ] [Configure the server, testing each logging level and compare to logging format.](https://github.com/reddepruebas/www/issues/28)
